version: '3.8'
services:
  cucai:
    build:
      context: .
    volumes:
      - .:/app
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
